function [BW] = erodeMask(MASK)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB,MASK) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 20-Sep-2021
%----------------------------------------------------

% Load Mask
BW = MASK;

% Erode mask with disk
radius = 4;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

end

