function [valueHeight] = obtenerAltura(fileNameDSM,filenameOrth,pointy,pointx,A,R)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB,MASK) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 25-Jul-2021
%% ----------------------------------------------------
coordenada=py.transformCoords.pixel2coord(pointx,pointy,filenameOrth);
 [xIntrinsic,yIntrinsic] = geographicToIntrinsic(R,coordenada{2},coordenada{1});
 valueHeight= A(uint16(yIntrinsic),uint16(xIntrinsic));
 %valueHeight=(uint16(valueHeight));
end

