function [BW,maskedImage] = segmentImageJuly15(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 25-Jul-2021
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Draw ROIs
%VALORES IMAGEN COMPLETA SAN ANTONIO 7 ANIOS
xPos = [2162.6982 2300.2928 2544.9054 6764.4730 6733.8964 6718.6081 6718.6081 6550.4369 6550.4369 6443.4189 6321.1126 3905.5631 2147.4099];
yPos = [2438.9820 4976.8378 7529.9820 7453.5405 6016.4414 6016.4414 6001.1532 4564.0541 4548.7658 3203.3964 1873.3153 2148.5045 2362.5405];

%VALORES IMAGEN MINIMIZADA SAN ANTONIO 7 ANIOS
xPos = [2684.6258 6754.0245 6523.2228 6523.2228 2459.8978 2654.2572];
yPos = [7586.5880 7416.5236 4185.2996 4179.2258 4391.8064 7629.1041];

m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

