function [BW,maskedImage] = segmentImageJuly15(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 25-Jul-2021
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Draw ROIs

xPos = [9851.3228 12597.2559 12891.2244 13111.7008 12984.7598 12450.2717 11722.0315 10619.6496 10238.8268 9817.9173 9837.9606];
yPos = [999.3248 1513.7697 2602.7894 3912.2854 5228.4626 6270.7146 6738.3917 6945.5059 4186.2106 2181.8799 985.9626];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

