function [maskedRGBImage] = segmentImageUsingColorThreshold(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 11-Aug-2021
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2lab(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 15.165;
channel1Max = 59.339;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 40.126;
channel2Max = 61.687;

% Define thresholds for channel 3 based on histogram settings
channel3Min = -64.399;
channel3Max = -48.707;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

[mask3]  = operationDilateBakground(BW);
maskedRGBImage= RGB .* uint8(mask3);

end
